# -*- coding: utf-8 -*-
# Generated by Django x.x.x on xxxx-xx-xx xx:xx
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('ticket', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
            ],
        ),
    ]
