# Generated by Django 2.1.4 on 2019-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=10, unique=True)),
                ('ticket', models.CharField(max_length=10, unique=True)),
                ('number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
