# Generated by Django 2.1.4 on 2019-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='news',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
